(rocq.theory
  (name ITreeExamples)
  (modules
    IntroductionSolutions
    Nimp
    LC
    STLC
    ReadmeExample
    ITreePredicatesExample
    MultiThreadedPrinting)
  (theories Stdlib ITree)
)

; Extraction is in a separate directory (extraction/) because dune's
; rocq.extraction assigns it another library name than ITreeExamples
